### PR TITLE
Fix link to slsa-framework/github-actions-demo

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by Brend-Smits** [comment]
Heey @raboof,
Thanks for your contribution! How did we miss this typo in the link?! 
Appreciate it a lot.

Could you please sign your commit so we can merge this PR? ``git commit -s -m "message here"``

**Comment by raboof** [comment]
> Heey @raboof, Thanks for your contribution! How did we miss this typo in the link?! Appreciate it a lot.

Sure!

> Could you please sign your commit so we can merge this PR? `git commit -s -m "message here"`

Actually it was already signed, but indeed not yet signed-off :). Updated!

**Comment by Brend-Smits** [comment]
You're absolutely right. We can merge now.
Are you using this SLSA-Provenance-Action?

Thank you again.

**Review by Brend-Smits — APPROVED** [review]

**Comment by raboof** [comment]
> Are you using this SLSA-Provenance-Action?

Not yet - I'm just getting familiar with the SLSA requirements and processes at this point.

One thing I'm running into is that we publish predominantly JVM artifacts (Java/Scala), and it's not so clear to me what would be the best place to publish the provenance attestations: on the one hand, it'd seem it'd make sense to publish the attestation along with the actual artifacts (e.g. at https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_3/2.6.18/). However, while we could definitely integrate this in our build process (and would not need the Action in that case), with that approach it seems we could never reach L3: this publishing is part of the user-defined build steps, and the [non-falsifiability](https://slsa.dev/spec/v0.1/requirements#non-falsifiable) requirement requires those don't have access to the signing key. Do you have any suggestions here?

I noticed in the README that this Action specifically targets L1 - is that just a matter of not having implemented the requirements for further levels (yet), or did you encounter any requirements that fundamentally cannot be met with this approach?

**Pull request merged**
